server:
  port: 8130

spring:
  profiles:
    active: dev #环境配置
  application:
    name: service-oss #服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyId: keyId
    keySecret: keySecret
    bucketName: srb-file-2021-06-06