server:
  port: 8120

spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-sms #服务名
  redis:
    host: 192.168.0.108
    port: 6379
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    #redis连接池
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1   #最大阻塞等待时间，负值表示没有限制，默认为-1
        max-idle: 8    #最大空闲连接，默认8
        min-idle: 0    #最小空闲连接，默认0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: 192.168.0.108
    port: 5672
    virtual-host: /srbhost
    username: hhp
    password: 123456


#阿里云短信
aliyun:
  sms:
    region-id: cn-shanghai
    key-id: LTAI5tRf9exKZvsN7iosbcAU
    key-secret: QW81vTiP4DupBwy8L8Vf90DBeCTcya
    template-code: 模版
    sign-name: 签名

#超时控制,openfeign默认的连接超时时间为1秒
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true #开启Feign对Sentinel的支持

logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口